name: sabujak_application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.5+1
  go_router: ^17.0.1
  animations: ^2.1.1
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  intl: any
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.2
  shared_preferences: ^2.5.4
  firebase_auth: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true


  assets:
    #- assets/images/
    - assets/icons/
    #- assets/json/
    - assets/fonts/


  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600

    - family: AritaBuri
      fonts:
        - asset: assets/fonts/AritaBuriKR-SemiBold.ttf
          weight: 600

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700